<?
$aMenuLinks = Array(
	Array(
		"#SOCIAL_LINK_1_TYPE#", 
		"#SOCIAL_LINK_1#", 
		Array(), 
		Array("SOCIAL"=>"#SOCIAL_LINK_1_TYPE#"), 
		"#SOCIAL_LINK_1_ACTIVE#" 
	),
	Array(
		"#SOCIAL_LINK_2_TYPE#", 
		"#SOCIAL_LINK_2#", 
		Array(), 
		Array("SOCIAL"=>"#SOCIAL_LINK_2_TYPE#"), 
		"#SOCIAL_LINK_2_ACTIVE#" 
	),
	Array(
		"#SOCIAL_LINK_3_TYPE#", 
		"#SOCIAL_LINK_3#", 
		Array(), 
		Array("SOCIAL"=>"#SOCIAL_LINK_3_TYPE#"), 
		"#SOCIAL_LINK_3_ACTIVE#" 
	)
);
?>